name: Rest API testing
run-name: Api is running tests
on: [push]
jobs:
    run-tests:
        strategy:
            fail-fast: false
        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12.2"

            - name: install Dependencies
              run: |
                pip install -r requirements.txt
                pip install pytest  
            - name: Run tests
              run: pytest

